name: lint
on: push
jobs:
  format:
    name: Check nix file format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix run github:kamadorueda/alejandra/1.1.0 -- \
              --check \
              --exclude ./configurations/yui/hardware-configuration.nix \
              --exclude ./configurations/ct-lt-02052/hardware-configuration.nix \
              .

  check:
    name: Check nix correctness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
