name: update
on:
  schedule:
    - cron: '0 4 * * 6'
  workflow_dispatch:
jobs:
  update:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.PR_CREATE_KEY }}
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GIT_SIGNING_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-committer-name: GitHub automation
          git-committer-email: tm@tlater.net
      - run: nix build -o before-update .#nixosConfigurations.yui.config.system.build.toplevel
      - run: nix flake update
      - run: nix build -o after-update .#nixosConfigurations.yui.config.system.build.toplevel
      - run: nix run gitlab:khumba/nvd -- diff before-update after-update > version-diff
      - run: rm before-update after-update
      - run: git commit -am 'flake.lock: Update' -m '' -m "$(cat version-diff)"
      - uses: peter-evans/create-pull-request@v3
        with:
          branch: bot/update
          delete-branch: true
          title: Update flake inputs
