name: update
on:
  schedule:
    - cron: '0 4 * * 6'
  workflow_dispatch:
jobs:
  update:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.PR_CREATE_KEY }}
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GIT_SIGNING_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-committer-name: GitHub automation
          git-committer-email: tm@tlater.net
      - name: Build reference pre-update system to compare to
        run: nix build -o before-update .#nixosConfigurations.yui.config.system.build.toplevel
      - name: Update flake inputs
        run: nix flake update
      - name: Build system to compare to pre-update system
        run: nix build -o after-update .#nixosConfigurations.yui.config.system.build.toplevel
      - name: Create version diff
        run: nix run --no-write-lock-file gitlab:khumba/nvd -- diff before-update after-update > version-diff
      - name: Clean symlinks we don't want to commit
        run: rm before-update after-update
      - name: Commit changes
        run: |
          git commit -am 'flake.lock: Update' -m '' -m "$(cat version-diff)"
      - name: Clean up uncommitted changes
        run: git clean -fxd
      - uses: peter-evans/create-pull-request@v3
        with:
          branch: bot/update
          delete-branch: true
          title: Update flake inputs
